version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      DB_USER: postgres
      DB_HOST: db
      DB_NAME: url_shortener
      DB_PASSWORD: postgres
      DB_PORT: 5432
      JWT_SECRET: your_jwt_secret
      GOOGLE_CLIENT_ID: your_google_client_id
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
